import { Arvore } from './arvore';

export const ARVORES_FRUTIFERAS: Arvore [] = [
  new Arvore (1, 'Pequi', '', -10.1782832, -48.3466243, "assets/icon/pequi.jpg",
    'Caryocar brasiliense: também chamado de pequizeiro, piqui, piquiá e pequiá, é uma árvore da família das cariocaráceas nativa do cerrado brasileiro. Seu fruto é muito utilizado na culinária sertaneja.'),
  new Arvore (2, 'Pequi', '', -10.1853802,-48.3510158, "assets/icon/pequi.jpg",
  'Caryocar brasiliense: também chamado de pequizeiro, piqui, piquiá e pequiá, é uma árvore da família das cariocaráceas nativa do cerrado brasileiro. Seu fruto é muito utilizado na culinária sertaneja.'),
  new Arvore (3, 'Pequi', '', -10.1792112,-48.3523614, "assets/icon/pequi.jpg",
  'Caryocar brasiliense: também chamado de pequizeiro, piqui, piquiá e pequiá, é uma árvore da família das cariocaráceas nativa do cerrado brasileiro. Seu fruto é muito utilizado na culinária sertaneja.'),
  new Arvore (4, 'Caja', '', -10.1776832,-48.3456243, "assets/icon/caja.jpg",
  'Spondias mombin ou Spondias lutea: também conhecida pelos nomes cajazeiro, cajá, cajá-mirim, cajazinha, é uma árvore que chega a medir até 25 metros, da família das anacardiáceas, de casca adstringente e emética, de polpa resinosa, ácida, comestível e saudável conhecidas como cajás.' ),
  new Arvore (5, 'Caja', '', -10.1723832,-48.3422243, "assets/icon/caja.jpg",
  'Spondias mombin ou Spondias lutea: também conhecida pelos nomes cajazeiro, cajá, cajá-mirim, cajazinha, é uma árvore que chega a medir até 25 metros, da família das anacardiáceas, de casca adstringente e emética, de polpa resinosa, ácida, comestível e saudável conhecidas como cajás.' ),
  new Arvore (6, 'Caja', '', -10.1787832,-48.3400043, "assets/icon/caja.jpg",
  'Spondias mombin ou Spondias lutea: também conhecida pelos nomes cajazeiro, cajá, cajá-mirim, cajazinha, é uma árvore que chega a medir até 25 metros, da família das anacardiáceas, de casca adstringente e emética, de polpa resinosa, ácida, comestível e saudável conhecidas como cajás.' ),
  new Arvore (7, 'Manga', '', -10.1803832,-48.3505243, "assets/icon/manga.jpg",
  'Mangifera indica é uma espécie de planta da família Anacardiaceae. Pode ser encontrada na forma nativa nas florestas do sul e sudeste da Ásia, tendo sido introduzida em várias regiões do Mundo.'),
  new Arvore (8, 'Manga', '', -10.1777832,-48.3444243, "assets/icon/manga.jpg",
  'Mangifera indica é uma espécie de planta da família Anacardiaceae. Pode ser encontrada na forma nativa nas florestas do sul e sudeste da Ásia, tendo sido introduzida em várias regiões do Mundo.'),
  new Arvore (9, 'Manga', '', -10.1799832,-48.3488243, "assets/icon/manga.jpg",
  'Mangifera indica é uma espécie de planta da família Anacardiaceae. Pode ser encontrada na forma nativa nas florestas do sul e sudeste da Ásia, tendo sido introduzida em várias regiões do Mundo.'),
  new Arvore (10, 'Jamelão', '', -10.1711832,-48.3433243, "assets/icon/jamelao.jpg",
  'O jamelão, jambo, jambolão, jamborão, baguaçu, jalão[1], joão-bolão, topin, manjelão, azeitona-preta, ameixa roxa, baga-de-freira, oliveira, brinco-de-viúva ou guapê  é o fruto da planta de mesmo nome da família Myrtaceae. A espécie é nativa da Índia.'),
  new Arvore (11, 'Jamelão', '', -10.1792112,-48.3523614, "assets/icon/jamelao.jpg",
  'O jamelão, jambo, jambolão, jamborão, baguaçu, jalão[1], joão-bolão, topin, manjelão, azeitona-preta, ameixa roxa, baga-de-freira, oliveira, brinco-de-viúva ou guapê  é o fruto da planta de mesmo nome da família Myrtaceae. A espécie é nativa da Índia.'),
  new Arvore (12, 'Jamelão', '', -10.1799832,-48.3403243, "assets/icon/jamelao.jpg",
  'O jamelão, jambo, jambolão, jamborão, baguaçu, jalão[1], joão-bolão, topin, manjelão, azeitona-preta, ameixa roxa, baga-de-freira, oliveira, brinco-de-viúva ou guapê  é o fruto da planta de mesmo nome da família Myrtaceae. A espécie é nativa da Índia.'),
];

export const ARVORES_MEDICINAIS: Arvore[] = [
  new Arvore (21, 'Abacate', '', -10.1712832,-48.3460243, "assets/icon/abacate.jpg",
  'O abacateiro, cujo fruto é o abacate, também designado como abacado, loiro-abacate e louro-abacate é uma espécie da família Lauraceae, de nome científico Persea americana.'),
  new Arvore (22, 'Abacate', '', -10.1853802,-48.3510158, "assets/icon/abacate.jpg",
  'O abacateiro, cujo fruto é o abacate, também designado como abacado, loiro-abacate e louro-abacate é uma espécie da família Lauraceae, de nome científico Persea americana.'),
  new Arvore (23, 'Boldo', '', -10.1715832,-48.3417843, "assets/icon/boldo.jpg",
  'O boldo serve para tratar má digestão, problemas do fígado, litíase biliar, gota, obstipação, cistite, flatulência, dor de cabeça e suores frio.'),
  new Arvore (24, 'Boldo', '', -10.1766832,-48.3454243, "assets/icon/boldo.jpg",
  'O boldo serve para tratar má digestão, problemas do fígado, litíase biliar, gota, obstipação, cistite, flatulência, dor de cabeça e suores frio.'),
  new Arvore (25, 'Boldo', '', -10.1853802,-48.3510158, "assets/icon/boldo.jpg",
  'O boldo serve para tratar má digestão, problemas do fígado, litíase biliar, gota, obstipação, cistite, flatulência, dor de cabeça e suores frio.'),
  new Arvore (26, 'Caju', '', -10.1853809,-48.3510258, "assets/icon/caju.jpg",
  'O cajueiro (nome científico Anacardium occidentale) é uma planta da família Anacardiaceae originária da região nordeste do Brasil, com arquitetura de copa tortuosa e de diferentes portes.'),
  new Arvore (27, 'Caju', '', -10.1790832,-48.3497243, "assets/icon/caju.jpg",
  'O cajueiro (nome científico Anacardium occidentale) é uma planta da família Anacardiaceae originária da região nordeste do Brasil, com arquitetura de copa tortuosa e de diferentes portes.'),
];
