import { Arvore } from './arvore';

export const ARVORES_FRUTIFERAS: Arvore [] = [
    { id: 1, name: 'Pequi', distancia: '', lat: -10.1782832, lng: -48.3466243, icon: "assets/icon/pequi.jpg",
    descricao: 'Caryocar brasiliense: também chamado de pequizeiro, piqui, piquiá e pequiá, é uma árvore da família das cariocaráceas nativa do cerrado brasileiro. Seu fruto é muito utilizado na culinária sertaneja.'},
    { id: 2, name: 'Pequi', distancia: '', lat: -10.1853802, lng: -48.3510158, icon: "assets/icon/pequi.jpg",
    descricao: 'Caryocar brasiliense: também chamado de pequizeiro, piqui, piquiá e pequiá, é uma árvore da família das cariocaráceas nativa do cerrado brasileiro. Seu fruto é muito utilizado na culinária sertaneja.'},
    { id: 3, name: 'Pequi', distancia: '', lat: -10.1792112, lng: -48.3523614, icon: "assets/icon/pequi.jpg",
    descricao: 'Caryocar brasiliense: também chamado de pequizeiro, piqui, piquiá e pequiá, é uma árvore da família das cariocaráceas nativa do cerrado brasileiro. Seu fruto é muito utilizado na culinária sertaneja.'},
    { id: 4, name: 'Caja', distancia: '', lat: -10.1776832, lng: -48.3456243, icon: "assets/icon/caja.jpg",
    descricao: 'Spondias mombin ou Spondias lutea: também conhecida pelos nomes cajazeiro, cajá, cajá-mirim, cajazinha, é uma árvore que chega a medir até 25 metros, da família das anacardiáceas, de casca adstringente e emética, de polpa resinosa, ácida, comestível e saudável conhecidas como cajás.' },
    { id: 5, name: 'Caja', distancia: '', lat: -10.1723832, lng: -48.3422243, icon: "assets/icon/caja.jpg",
    descricao: 'Spondias mombin ou Spondias lutea: também conhecida pelos nomes cajazeiro, cajá, cajá-mirim, cajazinha, é uma árvore que chega a medir até 25 metros, da família das anacardiáceas, de casca adstringente e emética, de polpa resinosa, ácida, comestível e saudável conhecidas como cajás.' },
    { id: 6, name: 'Caja', distancia: '', lat: -10.1787832, lng: -48.3400043, icon: "assets/icon/caja.jpg",
    descricao: 'Spondias mombin ou Spondias lutea: também conhecida pelos nomes cajazeiro, cajá, cajá-mirim, cajazinha, é uma árvore que chega a medir até 25 metros, da família das anacardiáceas, de casca adstringente e emética, de polpa resinosa, ácida, comestível e saudável conhecidas como cajás.' },
    { id: 7, name: 'Manga', distancia: '', lat: -10.1803832, lng: -48.3505243, icon: "assets/icon/manga.jpg",
    descricao: 'Mangifera indica é uma espécie de planta da família Anacardiaceae. Pode ser encontrada na forma nativa nas florestas do sul e sudeste da Ásia, tendo sido introduzida em várias regiões do Mundo.'},
    { id: 8, name: 'Manga', distancia: '', lat: -10.1777832, lng: -48.3444243, icon: "assets/icon/manga.jpg",
    descricao: 'Mangifera indica é uma espécie de planta da família Anacardiaceae. Pode ser encontrada na forma nativa nas florestas do sul e sudeste da Ásia, tendo sido introduzida em várias regiões do Mundo.'},
    { id: 9, name: 'Manga', distancia: '', lat: -10.1799832, lng: -48.3488243, icon: "assets/icon/manga.jpg",
    descricao: 'Mangifera indica é uma espécie de planta da família Anacardiaceae. Pode ser encontrada na forma nativa nas florestas do sul e sudeste da Ásia, tendo sido introduzida em várias regiões do Mundo.'},
    { id: 10, name: 'Jamelão', distancia: '', lat: -10.1711832, lng: -48.3433243, icon: "assets/icon/jamelao.jpg",
    descricao: 'O jamelão, jambo, jambolão, jamborão, baguaçu, jalão[1], joão-bolão, topin, manjelão, azeitona-preta, ameixa roxa, baga-de-freira, oliveira, brinco-de-viúva ou guapê  é o fruto da planta de mesmo nome da família Myrtaceae. A espécie é nativa da Índia.'},
    { id: 11, name: 'Jamelão', distancia: '', lat: -10.1792112, lng: -48.3523614, icon: "assets/icon/jamelao.jpg",
    descricao: 'O jamelão, jambo, jambolão, jamborão, baguaçu, jalão[1], joão-bolão, topin, manjelão, azeitona-preta, ameixa roxa, baga-de-freira, oliveira, brinco-de-viúva ou guapê  é o fruto da planta de mesmo nome da família Myrtaceae. A espécie é nativa da Índia.'},
    { id: 12, name: 'Jamelão', distancia: '', lat: -10.1799832, lng: -48.3403243, icon: "assets/icon/jamelao.jpg",
    descricao: 'O jamelão, jambo, jambolão, jamborão, baguaçu, jalão[1], joão-bolão, topin, manjelão, azeitona-preta, ameixa roxa, baga-de-freira, oliveira, brinco-de-viúva ou guapê  é o fruto da planta de mesmo nome da família Myrtaceae. A espécie é nativa da Índia.'},
];

export const ARVORES_MEDICINAIS: Arvore [] = [
    { id: 21, name: 'Abacate', distancia: '', lat: -10.1712832, lng: -48.3460243, icon: "assets/icon/abacate.jpg",
    descricao: 'O abacateiro, cujo fruto é o abacate, também designado como abacado, loiro-abacate e louro-abacate é uma espécie da família Lauraceae, de nome científico Persea americana.'},
    { id: 22, name: 'Abacate', distancia: '', lat: -10.1853802, lng: -48.3510158, icon: "assets/icon/abacate.jpg",
    descricao: 'O abacateiro, cujo fruto é o abacate, também designado como abacado, loiro-abacate e louro-abacate é uma espécie da família Lauraceae, de nome científico Persea americana.'},
    { id: 23, name: 'Boldo', distancia: '', lat: -10.1715832, lng: -48.3417843, icon: "assets/icon/boldo.jpg",
    descricao: 'O boldo serve para tratar má digestão, problemas do fígado, litíase biliar, gota, obstipação, cistite, flatulência, dor de cabeça e suores frio.'},
    { id: 24, name: 'Boldo', distancia: '', lat: -10.1766832, lng: -48.3454243, icon: "assets/icon/boldo.jpg",
    descricao: 'O boldo serve para tratar má digestão, problemas do fígado, litíase biliar, gota, obstipação, cistite, flatulência, dor de cabeça e suores frio.'},
    { id: 25, name: 'Boldo', distancia: '', lat: -10.1853802, lng: -48.3510158, icon: "assets/icon/boldo.jpg",
    descricao: 'O boldo serve para tratar má digestão, problemas do fígado, litíase biliar, gota, obstipação, cistite, flatulência, dor de cabeça e suores frio.'},
    { id: 26, name: 'Caju', distancia: '', lat: -10.1853809, lng: -48.3510258, icon: "assets/icon/caju.jpg",
    descricao: 'O cajueiro (nome científico Anacardium occidentale) é uma planta da família Anacardiaceae originária da região nordeste do Brasil, com arquitetura de copa tortuosa e de diferentes portes.'},
    { id: 27, name: 'Caju', distancia: '', lat: -10.1790832, lng: -48.3497243, icon: "assets/icon/caju.jpg",
    descricao: 'O cajueiro (nome científico Anacardium occidentale) é uma planta da família Anacardiaceae originária da região nordeste do Brasil, com arquitetura de copa tortuosa e de diferentes portes.'},
];
